# Generated by Django 3.1.4 on 2020-12-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('model', models.CharField(blank=True, choices=[('gasoline', '휘발유'), ('diesel', '디젤')], max_length=100, null=True)),
                ('gear', models.TextField()),
                ('detail', models.TextField()),
            ],
        ),
    ]
