# Generated by Django 3.1.4 on 2020-12-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campingcar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
