# Generated by Django 3.1.4 on 2020-12-08 03:54

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('campingcar', '0002_auto_20201208_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=1010, size=10),
        ),
    ]
