# Generated by Django 3.1.4 on 2020-12-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campingcar', '0003_auto_20201208_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(choices=[('gasoline', '가솔린'), ('diesel', '디젤')], max_length=100),
        ),
    ]
