# Generated by Django 3.1.4 on 2020-12-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campingcar', '0004_auto_20201208_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
