# Generated by Django 3.1.4 on 2020-12-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campingcar', '0006_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/<django.db.models.fields.CharField>'),
        ),
    ]
