# Generated by Django 3.1.4 on 2020-12-08 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campingcar', '0008_auto_20201208_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='car',
            name='file',
        ),
        migrations.RemoveField(
            model_name='car',
            name='gear',
        ),
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.RemoveField(
            model_name='car',
            name='type',
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campingcar.car')),
            ],
        ),
    ]
