# Generated by Django 3.1.4 on 2020-12-08 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campingcar', '0010_detailmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailmodel',
            old_name='car',
            new_name='Model',
        ),
        migrations.RemoveField(
            model_name='model',
            name='price',
        ),
    ]
