# Generated by Django 3.1.4 on 2020-12-08 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campingcar', '0011_auto_20201208_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campingcar.car')),
            ],
        ),
        migrations.RemoveField(
            model_name='model',
            name='car',
        ),
        migrations.DeleteModel(
            name='DetailModel',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
