# Generated by Django 3.1.4 on 2020-12-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campingcar', '0012_auto_20201208_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option_type',
            field=models.CharField(choices=[('AirConditioner', '냉난방'), ('DoorAndWindow', '도어 & 창문'), ('Earning', '어닝'), ('Battery', '배터리'), ('Charger', 'AC 충전기'), ('Inverter', '인버터'), ('SolarPanel', '태양광시스템'), ('ETC', '기타')], default='ETC', max_length=100),
        ),
    ]
