# Generated by Django 3.1.4 on 2020-12-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campingcar', '0013_option_option_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='explanation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
