# Generated by Django 3.1.4 on 2020-12-08 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campingcar', '0015_auto_20201208_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='campingcar.car'),
        ),
    ]
