# Generated by Django 3.1.4 on 2020-12-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campingcar', '0016_auto_20201208_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='car',
        ),
        migrations.AddField(
            model_name='option',
            name='car',
            field=models.ManyToManyField(to='campingcar.Car'),
        ),
    ]
