# Generated by Django 3.1.4 on 2020-12-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campingcar', '0017_auto_20201208_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='car',
            field=models.ManyToManyField(blank=True, null=True, to='campingcar.Car'),
        ),
    ]
