# Generated by Django 3.1.4 on 2020-12-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campingcar', '0019_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('TruckCamper', '트럭캠퍼'), ('TruckBase', '트럭베이스'), ('VanBase', '밴베이스'), ('SpecificPurpose', '특수목적'), ('Trailer', '트레일러')], default='TruckCamper', max_length=100),
        ),
        migrations.AlterField(
            model_name='option',
            name='car',
            field=models.ManyToManyField(blank=True, to='campingcar.Car'),
        ),
    ]
