# Generated by Django 3.1.4 on 2020-12-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campingcar', '0020_auto_20201211_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='explanation',
            field=models.TextField(default='차량 설명을 입력하세요.'),
        ),
    ]
