# Generated by Django 3.1.4 on 2020-12-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campingcar', '0021_car_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/options'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/car'),
        ),
    ]
