# Generated by Django 3.1.1 on 2020-12-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campingcar', '0024_car_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('business_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('ceo_name', models.CharField(max_length=100)),
                ('car', models.ManyToManyField(blank=True, to='campingcar.Car')),
            ],
        ),
    ]
