# Generated by Django 3.1.1 on 2020-12-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campingcar', '0025_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='explanation',
            field=models.TextField(default='', help_text='차량의 설명을 입력하세요'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, help_text='차량의 이미지를 업로드하세요', null=True, upload_to='images/car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(help_text='차량의 이름을 입력하세요', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=0, help_text='차량의 가격을 입력하세요'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('TruckCamper', '트럭캠퍼'), ('TruckBase', '트럭베이스'), ('VanBase', '밴베이스'), ('SpecificPurpose', '특수목적'), ('Trailer', '트레일러')], default='TruckCamper', help_text='차량의 종류를 선택하세요', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(help_text='제작사의 주소를 입력하세요', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='business_number',
            field=models.CharField(help_text='제작사의 사업자번호를 입력하세요', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='car',
            field=models.ManyToManyField(blank=True, help_text='제작사가 만드는 차량들을 선택하세요(복수선택 가능)', to='campingcar.Car'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ceo_name',
            field=models.CharField(help_text='제작사의 대표자명을 입력하세요', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='제작사의 상호명을 입력하세요', max_length=100),
        ),
        migrations.AlterField(
            model_name='option',
            name='car',
            field=models.ManyToManyField(blank=True, help_text='옵션이 적용가능한 차량들을 선택하세요(복수선택 가능)', to='campingcar.Car'),
        ),
        migrations.AlterField(
            model_name='option',
            name='explanation',
            field=models.CharField(blank=True, help_text='옵션의 설명을 입력하세요', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='image',
            field=models.ImageField(blank=True, help_text='옵션의 이미지를 업로드하세요', null=True, upload_to='images/options'),
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(help_text='옵션의 이름을 입력하세요', max_length=100),
        ),
        migrations.AlterField(
            model_name='option',
            name='price',
            field=models.IntegerField(default=0, help_text='옵션의 가격을 입력하세요'),
        ),
        migrations.AlterField(
            model_name='option',
            name='type',
            field=models.CharField(choices=[('AirConditioner', '냉난방'), ('DoorAndWindow', '도어 & 창문'), ('Earning', '어닝'), ('Battery', '배터리'), ('Charger', 'AC 충전기'), ('Inverter', '인버터'), ('SolarPanel', '태양광시스템'), ('ETC', '기타')], default='ETC', help_text='옵션의 종류를 선택하세요', max_length=100),
        ),
    ]
