# Generated by Django 3.1.4 on 2020-12-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campingcar', '0029_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='consumption',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='education',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='vat',
        ),
        migrations.AddField(
            model_name='tax',
            name='name',
            field=models.CharField(default='세금', help_text='세금의 항목명을 입력하세요', max_length=100),
        ),
        migrations.AddField(
            model_name='tax',
            name='percentage',
            field=models.IntegerField(default=0, help_text='세금의 비율(퍼센트)을 입력하세요. *숫자만 입력 가능!'),
        ),
    ]
